### ISSUE TITLE
IE9+MathPlayer not working correctly

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-website#25]
Looks like MathJax detects MathPlayer, switched to NativeMML but MathPlayer isn't kicking in.

**Comment by pkra** [comment]
@dpvc is there anything beyond switching to NativeMML that MathJax should do?

**Comment by dpvc** [comment]
Yes, MathJax has to do several delicate operations to get MathPlayer set up and running.  It has been fragile in the past, and I didn't run the test suite with MathPlayer (since it no longer works with later versions of MathJax).  I did run it by hand on a few examples, and it did seem to work.  I don't know if the new web framework might be causing problems with it.  Can you get it to work on one of the MathJax sample pages from the CDN?

What version of MathPlayer are you using?  Is it their new incarnation?

**Comment by pkra** [comment]
> I don't know if the new web framework might be causing problems with it. 

Yes, that was my first thought as well.

> Can you get it to work on one of the MathJax sample pages from the CDN?

On the CDN samples, MathJax does not switch to NativeMML; when I switch manually I get the MathPlayer submenu so some detection is still working. But MathLpayer is not kicking in.

> What version of MathPlayer are you using? Is it their new incarnation?

No, just MathPlayer 3.

FYI, this came via Neil and Steve Noble who might be able to add more information.

**Comment by NSoiffer** [comment]
In general, MathJax does seem to connect up to MathPlayer. But Steve found a few cases where it isn't. It could be some timing issues with MathJax and the MathPlayer BHO running at the wrong times.
I'm running the new MathPlayer with IE11 in enterprise mode and if I switch it to use MathML, it kicks in properly. Switching is really hard though due to the menus not working right -- I filed a separate issue on that.

**Comment by Steve-Noble** [comment]
Just to fill in a few details from an earlier email exchange...
For some reason this mostly happens on pages on the mathjax.org domain. For instance, these two pages use MathJax (though they use older versions of MathJax 2.4 and 2.3), and when I use IE9+MathPlayer3 and tell the site to pass MathML, MathPlayer gets triggered appropriately:
http://www.onemathematicalcat.org/Math/Algebra_II_obj/factorial_notation.htm
http://chemistry.alanearhart.org/Quizzes/mathjaxtest.html
I cannot seem to get pages on mathjax.org to fire MathPlayer3 in IE9 at all.

**Comment by pkra** [comment]
To add @Steve-Noble 's comment via email, another example is math.SE where (after I spun up my VM this morning) I a) don't get MathJax to switch automatically to NativeMML and b) manually switching to NativeMML does not make MathPlayer kick-in (in this case you see the annotation-xml's TeX but MathML is correctly in the page)

Time to move this upstream? It's apparently not specific to our website anymore but to v2.5+ in general?

**Comment by dpvc** [comment]
Yes it is probably MathJax not the website.  And even if it were something on the website, it would be good to be able to work around it in MathJax.

**Comment by pkra** [comment]
Closing in favor of https://github.com/mathjax/MathJax/issues/1074
