### ISSUE TITLE
update copyright 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-website#56]
I hear it's 2016.

**Comment by dpvc** [comment]
I don't think you want to change the copyright year.  It is supposed to indicate the date of first publication, not the current date, and establishes how far back your copyright claim extends.  If you move this to a later date, then someone else who made a copy in the meantime (say in 2015) can establish _their_ claim to our material as preceding ours.  If you want to include 2016 in the date, then I'd recommend using a collection of dates (e.g., `2014,2016`) or a range (e.g., `2014-2016`).  But I would not remove the original date, since that is important.

**Comment by pkra** [comment]
>  establishes how far back your copyright claim extends [...]
>  can establish their claim to our material as preceding ours.

Not really since a site owner could set it to whatever they want. [This](https://web.archive.org/web/20090601000000*/http://mathjax.org) on the other hand is harder to forge. As is this repository, the docs repository etc.

>  I'd recommend using a collection of dates

Sure. Why not just make a PR?

> But I would not remove the original date, since that is important.

The redesign poses some interesting questions on when the content in its current was created.

**Comment by dpvc** [comment]
> Not really since a site owner could set it to whatever they want

Yes, yes, of course someone could set it to whatever they want (and someone in print could do the same), but that is what the date is _supposed_ to indicate, and it gives people looking at the page an idea of the historical extent of the page.  I didn't mean "establishes" in the legal sense, as forgery is always possible.  I meant that by setting it to 2016, you essentially _give up_ the claim to anything earlier.

I see that you have changed it in a recent commit, which I appreciate.
